title = "Pradeen Krishnamoorthy"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Ambur,tiruppathur, India"
favicon = "/favicon.ico"
firstName = "Pradeen"
lastName = "Krishnamoorthy"
phone = "0987654321"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/kp-editz-544641321/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Pradeensk1/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
